<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NP-SADEKUNLE" name="ChangePasswordTest" tests="3" failures="1" timestamp="14 Feb 2017 11:20:31 GMT" time="150.019" errors="0">
  <testcase name="changepasswordtest" time="49.486" classname="Suite.ChangePasswordTest"/>
  <testcase name="changepasswordtest" time="47.773" classname="Suite.ChangePasswordTest"/>
  <testcase name="changepasswordtest" time="49.246" classname="Suite.ChangePasswordTest">
    <failure type="java.lang.AssertionError" message="expected [FAILURE] but found [SUCCESS]">
      <![CDATA[java.lang.AssertionError: expected [FAILURE] but found [SUCCESS]
	at Suite.ChangePasswordTest.changepasswordtest(ChangePasswordTest.java:46)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- changepasswordtest -->
</testsuite> <!-- ChangePasswordTest -->
